//! First-level administrative divisions keyed by ISO 3166-1 alpha-2 country code.
//! Display names are stored in English and persisted as the user's `region` value.

/// Returns first-level regions for `code`, when defined.
#[must_use]
pub fn regions_for_country_code(code: &str) -> Option<&'static [&'static str]> {
    REGIONS_BY_COUNTRY
        .iter()
        .find(|(country, _)| *country == code)
        .map(|(_, regions)| *regions)
}

/// Placeholder label for the region `<select>` on the profile edit form.
#[must_use]
pub fn region_prompt_for_country_code(code: &str) -> &'static str {
    match code {
        "US" => "Select a state…",
        "CA" | "MX" => "Select a province…",
        "CH" => "Select a canton…",
        "GB" => "Select a country…",
        "IE" => "Select a county…",
        "DE" | "AT" => "Select a state…",
        "FR" | "IT" | "ES" | "PL" | "RO" | "UA" | "TR" | "RU" => "Select a region…",
        "NL" | "BE" => "Select a province…",
        _ => "Select a region…",
    }
}

const US: &[&str] = &[
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
];

const CA: &[&str] = &[
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon",
];

const AL: &[&str] = &[
    "Berat",
    "Dibër",
    "Durrës",
    "Elbasan",
    "Fier",
    "Gjirokastër",
    "Korçë",
    "Kukës",
    "Lezhë",
    "Shkodër",
    "Tirana",
    "Vlorë",
];

const AD: &[&str] = &[
    "Andorra la Vella",
    "Canillo",
    "Encamp",
    "Escaldes-Engordany",
    "La Massana",
    "Ordino",
    "Sant Julià de Lòria",
];

const AT: &[&str] = &[
    "Burgenland",
    "Carinthia",
    "Lower Austria",
    "Salzburg",
    "Styria",
    "Tyrol",
    "Upper Austria",
    "Vienna",
    "Vorarlberg",
];

const AM: &[&str] = &[
    "Aragatsotn",
    "Ararat",
    "Armavir",
    "Gegharkunik",
    "Kotayk",
    "Lori",
    "Shirak",
    "Syunik",
    "Tavush",
    "Vayots Dzor",
    "Yerevan",
];

const AZ: &[&str] = &[
    "Absheron",
    "Agdam",
    "Agdash",
    "Aghjabadi",
    "Agstafa",
    "Agsu",
    "Astara",
    "Baku",
    "Balakan",
    "Barda",
    "Beylagan",
    "Bilasuvar",
    "Dashkasan",
    "Fuzuli",
    "Gadabay",
    "Ganja",
    "Gobustan",
    "Goranboy",
    "Goychay",
    "Goygol",
    "Hajigabul",
    "Imishli",
    "Ismailli",
    "Jabrayil",
    "Jalilabad",
    "Kalbajar",
    "Khachmaz",
    "Khankendi",
    "Khizi",
    "Khojali",
    "Kurdamir",
    "Lachin",
    "Lankaran",
    "Lerik",
    "Masally",
    "Mingachevir",
    "Naftalan",
    "Nakhchivan",
    "Neftchala",
    "Oghuz",
    "Qabala",
    "Qakh",
    "Qazakh",
    "Quba",
    "Qubadli",
    "Qusar",
    "Saatly",
    "Sabirabad",
    "Salyan",
    "Samukh",
    "Shaki",
    "Shamakhi",
    "Shamkir",
    "Sharur",
    "Shirvan",
    "Shusha",
    "Siazan",
    "Sumqayit",
    "Tartar",
    "Tovuz",
    "Ujar",
    "Yardimli",
    "Yevlakh",
    "Zangilan",
    "Zaqatala",
    "Zardab",
];

const BY: &[&str] = &[
    "Brest",
    "Gomel",
    "Grodno",
    "Minsk",
    "Minsk City",
    "Mogilev",
    "Vitebsk",
];

const BE: &[&str] = &[
    "Antwerp",
    "Brussels-Capital",
    "East Flanders",
    "Flemish Brabant",
    "Hainaut",
    "Liège",
    "Limburg",
    "Luxembourg",
    "Namur",
    "Walloon Brabant",
    "West Flanders",
];

const BA: &[&str] = &[
    "Brčko District",
    "Federation of Bosnia and Herzegovina",
    "Republika Srpska",
];

const BG: &[&str] = &[
    "Blagoevgrad",
    "Burgas",
    "Dobrich",
    "Gabrovo",
    "Haskovo",
    "Kardzhali",
    "Kyustendil",
    "Lovech",
    "Montana",
    "Pazardzhik",
    "Pernik",
    "Pleven",
    "Plovdiv",
    "Razgrad",
    "Ruse",
    "Shumen",
    "Silistra",
    "Sliven",
    "Smolyan",
    "Sofia",
    "Sofia City",
    "Stara Zagora",
    "Targovishte",
    "Varna",
    "Veliko Tarnovo",
    "Vidin",
    "Vratsa",
    "Yambol",
];

const HR: &[&str] = &[
    "Bjelovar-Bilogora",
    "Brod-Posavina",
    "Dubrovnik-Neretva",
    "Istria",
    "Karlovac",
    "Koprivnica-Križevci",
    "Krapina-Zagorje",
    "Lika-Senj",
    "Međimurje",
    "Osijek-Baranja",
    "Požega-Slavonia",
    "Primorje-Gorski Kotar",
    "Šibenik-Knin",
    "Sisak-Moslavina",
    "Split-Dalmatia",
    "Varaždin",
    "Virovitica-Podravina",
    "Vukovar-Syrmia",
    "Zadar",
    "Zagreb",
    "Zagreb City",
];

const CY: &[&str] = &[
    "Famagusta",
    "Kyrenia",
    "Larnaca",
    "Limassol",
    "Nicosia",
    "Paphos",
];

const CZ: &[&str] = &[
    "Central Bohemian",
    "Hradec Králové",
    "Karlovy Vary",
    "Liberec",
    "Moravian-Silesian",
    "Olomouc",
    "Pardubice",
    "Plzeň",
    "Prague",
    "South Bohemian",
    "South Moravian",
    "Ústí nad Labem",
    "Vysočina",
    "Zlín",
];

const DK: &[&str] = &[
    "Capital Region",
    "Central Denmark",
    "North Denmark",
    "Southern Denmark",
    "Zealand",
];

const EE: &[&str] = &[
    "Harju",
    "Hiiu",
    "Ida-Viru",
    "Jõgeva",
    "Järva",
    "Lääne",
    "Lääne-Viru",
    "Põlva",
    "Pärnu",
    "Rapla",
    "Saare",
    "Tartu",
    "Valga",
    "Viljandi",
    "Võru",
];

const FI: &[&str] = &[
    "Central Finland",
    "Central Ostrobothnia",
    "Kainuu",
    "Kymenlaakso",
    "Lapland",
    "North Karelia",
    "North Ostrobothnia",
    "North Savo",
    "Ostrobothnia",
    "Päijät-Häme",
    "Pirkanmaa",
    "Satakunta",
    "South Karelia",
    "South Ostrobothnia",
    "South Savo",
    "Southwest Finland",
    "Tavastia Proper",
    "Uusimaa",
];

const FR: &[&str] = &[
    "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté",
    "Brittany",
    "Centre-Val de Loire",
    "Corsica",
    "Grand Est",
    "Hauts-de-France",
    "Île-de-France",
    "Normandy",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Pays de la Loire",
    "Provence-Alpes-Côte d'Azur",
];

const GE: &[&str] = &[
    "Adjara",
    "Guria",
    "Imereti",
    "Kakheti",
    "Kvemo Kartli",
    "Mtskheta-Mtianeti",
    "Racha-Lechkhumi and Kvemo Svaneti",
    "Samegrelo-Zemo Svaneti",
    "Samtskhe-Javakheti",
    "Shida Kartli",
    "Tbilisi",
];

const DE: &[&str] = &[
    "Baden-Württemberg",
    "Bavaria",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse",
    "Lower Saxony",
    "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia",
    "Rhineland-Palatinate",
    "Saarland",
    "Saxony",
    "Saxony-Anhalt",
    "Schleswig-Holstein",
    "Thuringia",
];

const GR: &[&str] = &[
    "Attica",
    "Central Greece",
    "Central Macedonia",
    "Crete",
    "East Macedonia and Thrace",
    "Epirus",
    "Ionian Islands",
    "North Aegean",
    "Peloponnese",
    "South Aegean",
    "Thessaly",
    "West Greece",
    "West Macedonia",
];

const HU: &[&str] = &[
    "Bács-Kiskun",
    "Baranya",
    "Békés",
    "Borsod-Abaúj-Zemplén",
    "Budapest",
    "Csongrád-Csanád",
    "Fejér",
    "Győr-Moson-Sopron",
    "Hajdú-Bihar",
    "Heves",
    "Jász-Nagykun-Szolnok",
    "Komárom-Esztergom",
    "Nógrád",
    "Pest",
    "Somogy",
    "Szabolcs-Szatmár-Bereg",
    "Tolna",
    "Vas",
    "Veszprém",
    "Zala",
];

const IS: &[&str] = &[
    "Capital Region",
    "Eastern",
    "Northeastern",
    "Northwestern",
    "Southern",
    "Southern Peninsula",
    "Western",
    "Westfjords",
];

const IE: &[&str] = &[
    "Carlow",
    "Cavan",
    "Clare",
    "Cork",
    "Donegal",
    "Dublin",
    "Galway",
    "Kerry",
    "Kildare",
    "Kilkenny",
    "Laois",
    "Leitrim",
    "Limerick",
    "Longford",
    "Louth",
    "Mayo",
    "Meath",
    "Monaghan",
    "Offaly",
    "Roscommon",
    "Sligo",
    "Tipperary",
    "Waterford",
    "Westmeath",
    "Wexford",
    "Wicklow",
];

const IT: &[&str] = &[
    "Abruzzo",
    "Aosta Valley",
    "Apulia",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli-Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardy",
    "Marche",
    "Molise",
    "Piedmont",
    "Sardinia",
    "Sicily",
    "Trentino-Alto Adige",
    "Tuscany",
    "Umbria",
    "Veneto",
];

const LV: &[&str] = &["Kurzeme", "Latgale", "Riga", "Vidzeme", "Zemgale"];

const LI: &[&str] = &[
    "Balzers",
    "Eschen",
    "Gamprin",
    "Mauren",
    "Planken",
    "Ruggell",
    "Schaan",
    "Schellenberg",
    "Triesen",
    "Triesenberg",
    "Vaduz",
];

const LT: &[&str] = &[
    "Alytus",
    "Kaunas",
    "Klaipėda",
    "Marijampolė",
    "Panevėžys",
    "Šiauliai",
    "Tauragė",
    "Telšiai",
    "Utena",
    "Vilnius",
];

const LU: &[&str] = &[
    "Capellen",
    "Clervaux",
    "Diekirch",
    "Echternach",
    "Esch-sur-Alzette",
    "Grevenmacher",
    "Luxembourg",
    "Mersch",
    "Redange",
    "Remich",
    "Vianden",
    "Wiltz",
];

const MT: &[&str] = &["Central", "Gozo", "Northern", "South Eastern", "Southern"];

const MX: &[&str] = &[
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Ciudad de México",
    "Coahuila",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "México",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas",
];

const MD: &[&str] = &[
    "Anenii Noi",
    "Basarabeasca",
    "Bălți",
    "Bender",
    "Briceni",
    "Cahul",
    "Călărași",
    "Cantemir",
    "Căușeni",
    "Chișinău",
    "Cimișlia",
    "Criuleni",
    "Dondușeni",
    "Drochia",
    "Dubăsari",
    "Edineț",
    "Fălești",
    "Florești",
    "Gagauzia",
    "Glodeni",
    "Hîncești",
    "Ialoveni",
    "Leova",
    "Nisporeni",
    "Ocnița",
    "Orhei",
    "Rezina",
    "Rîșcani",
    "Sîngerei",
    "Soroca",
    "Strășeni",
    "Șoldănești",
    "Ștefan Vodă",
    "Taraclia",
    "Telenești",
    "Transnistria",
    "Ungheni",
];

const MC: &[&str] = &["Monaco"];

const ME: &[&str] = &[
    "Andrijevica",
    "Bar",
    "Berane",
    "Bijelo Polje",
    "Budva",
    "Cetinje",
    "Danilovgrad",
    "Gusinje",
    "Herceg Novi",
    "Kolašin",
    "Kotor",
    "Mojkovac",
    "Nikšić",
    "Petnjica",
    "Plav",
    "Pljevlja",
    "Plužine",
    "Podgorica",
    "Rožaje",
    "Šavnik",
    "Tivat",
    "Ulcinj",
    "Žabljak",
];

const NL: &[&str] = &[
    "Drenthe",
    "Flevoland",
    "Friesland",
    "Gelderland",
    "Groningen",
    "Limburg",
    "North Brabant",
    "North Holland",
    "Overijssel",
    "South Holland",
    "Utrecht",
    "Zeeland",
];

const MK: &[&str] = &[
    "Eastern",
    "Northeastern",
    "Pelagonia",
    "Polog",
    "Skopje",
    "Southeastern",
    "Southwestern",
    "Vardar",
];

const NO: &[&str] = &[
    "Agder",
    "Innlandet",
    "Møre og Romsdal",
    "Nordland",
    "Oslo",
    "Rogaland",
    "Telemark",
    "Troms",
    "Trøndelag",
    "Vestfold",
    "Vestland",
    "Akershus",
    "Buskerud",
    "Finnmark",
];

const PL: &[&str] = &[
    "Greater Poland",
    "Holy Cross",
    "Kuyavian-Pomeranian",
    "Lesser Poland",
    "Lower Silesian",
    "Lublin",
    "Lubusz",
    "Łódź",
    "Masovian",
    "Opole",
    "Podlaskie",
    "Pomeranian",
    "Silesian",
    "Subcarpathian",
    "Warmian-Masurian",
    "West Pomeranian",
];

const PT: &[&str] = &[
    "Aveiro",
    "Azores",
    "Beja",
    "Braga",
    "Bragança",
    "Castelo Branco",
    "Coimbra",
    "Évora",
    "Faro",
    "Guarda",
    "Leiria",
    "Lisbon",
    "Madeira",
    "Portalegre",
    "Porto",
    "Santarém",
    "Setúbal",
    "Viana do Castelo",
    "Vila Real",
    "Viseu",
];

const RO: &[&str] = &[
    "Alba",
    "Arad",
    "Argeș",
    "Bacău",
    "Bihor",
    "Bistrița-Năsăud",
    "Botoșani",
    "Brăila",
    "Brașov",
    "Bucharest",
    "Buzău",
    "Călărași",
    "Caraș-Severin",
    "Cluj",
    "Constanța",
    "Covasna",
    "Dâmbovița",
    "Dolj",
    "Galați",
    "Giurgiu",
    "Gorj",
    "Harghita",
    "Hunedoara",
    "Ialomița",
    "Iași",
    "Ilfov",
    "Maramureș",
    "Mehedinți",
    "Mureș",
    "Neamț",
    "Olt",
    "Prahova",
    "Sălaj",
    "Satu Mare",
    "Sibiu",
    "Suceava",
    "Teleorman",
    "Timiș",
    "Tulcea",
    "Vâlcea",
    "Vaslui",
    "Vrancea",
];

const RU: &[&str] = &[
    "Adygea",
    "Altai",
    "Altai Krai",
    "Amur",
    "Arkhangelsk",
    "Astrakhan",
    "Bashkortostan",
    "Belgorod",
    "Bryansk",
    "Buryatia",
    "Chechnya",
    "Chelyabinsk",
    "Chukotka",
    "Chuvashia",
    "Dagestan",
    "Ingushetia",
    "Irkutsk",
    "Ivanovo",
    "Jewish Autonomous Oblast",
    "Kabardino-Balkaria",
    "Kaliningrad",
    "Kalmykia",
    "Kaluga",
    "Kamchatka",
    "Karachay-Cherkessia",
    "Karelia",
    "Kemerovo",
    "Khabarovsk",
    "Khakassia",
    "Khanty-Mansi",
    "Kirov",
    "Komi",
    "Kostroma",
    "Krasnodar",
    "Krasnoyarsk",
    "Kurgan",
    "Kursk",
    "Leningrad",
    "Lipetsk",
    "Magadan",
    "Mari El",
    "Mordovia",
    "Moscow",
    "Moscow Oblast",
    "Murmansk",
    "Nenets",
    "Nizhny Novgorod",
    "North Ossetia-Alania",
    "Novgorod",
    "Novosibirsk",
    "Omsk",
    "Orenburg",
    "Oryol",
    "Penza",
    "Perm",
    "Primorsky",
    "Pskov",
    "Rostov",
    "Ryazan",
    "Saint Petersburg",
    "Sakha",
    "Sakhalin",
    "Samara",
    "Saratov",
    "Smolensk",
    "Stavropol",
    "Sverdlovsk",
    "Tambov",
    "Tatarstan",
    "Tomsk",
    "Tula",
    "Tver",
    "Tyumen",
    "Tyva",
    "Udmurtia",
    "Ulyanovsk",
    "Vladimir",
    "Volgograd",
    "Vologda",
    "Voronezh",
    "Yamalo-Nenets",
    "Yaroslavl",
    "Zabaykalsky",
];

const SM: &[&str] = &[
    "Acquaviva",
    "Borgo Maggiore",
    "Chiesanuova",
    "Domagnano",
    "Faetano",
    "Fiorentino",
    "Montegiardino",
    "San Marino",
    "Serravalle",
];

const RS: &[&str] = &[
    "Belgrade",
    "Bor",
    "Braničevo",
    "Central Banat",
    "Jablanica",
    "Kolubara",
    "Mačva",
    "Moravica",
    "Nišava",
    "North Bačka",
    "North Banat",
    "Pčinja",
    "Pirot",
    "Podunavlje",
    "Pomoravlje",
    "Rasina",
    "Raška",
    "South Bačka",
    "South Banat",
    "Srem",
    "Šumadija",
    "Toplica",
    "West Bačka",
    "Zlatibor",
];

const SK: &[&str] = &[
    "Banská Bystrica",
    "Bratislava",
    "Košice",
    "Nitra",
    "Prešov",
    "Trenčín",
    "Trnava",
    "Žilina",
];

const SI: &[&str] = &[
    "Gorenjska",
    "Goriška",
    "Jugovzhodna Slovenija",
    "Koroška",
    "Obalno-kraška",
    "Osrednjeslovenska",
    "Podravska",
    "Pomurska",
    "Posavska",
    "Primorsko-notranjska",
    "Savinjska",
    "Zasavska",
];

const ES: &[&str] = &[
    "Andalusia",
    "Aragon",
    "Asturias",
    "Balearic Islands",
    "Basque Country",
    "Canary Islands",
    "Cantabria",
    "Castile and León",
    "Castile-La Mancha",
    "Catalonia",
    "Ceuta",
    "Extremadura",
    "Galicia",
    "La Rioja",
    "Madrid",
    "Melilla",
    "Murcia",
    "Navarre",
    "Valencian Community",
];

const SE: &[&str] = &[
    "Blekinge",
    "Dalarna",
    "Gävleborg",
    "Gotland",
    "Halland",
    "Jämtland",
    "Jönköping",
    "Kalmar",
    "Kronoberg",
    "Norrbotten",
    "Örebro",
    "Östergötland",
    "Skåne",
    "Södermanland",
    "Stockholm",
    "Uppsala",
    "Värmland",
    "Västerbotten",
    "Västernorrland",
    "Västmanland",
    "Västra Götaland",
];

const CH: &[&str] = &[
    "Aargau",
    "Appenzell Ausserrhoden",
    "Appenzell Innerrhoden",
    "Basel-Landschaft",
    "Basel-Stadt",
    "Bern",
    "Fribourg",
    "Geneva",
    "Glarus",
    "Grisons",
    "Jura",
    "Lucerne",
    "Neuchâtel",
    "Nidwalden",
    "Obwalden",
    "Schaffhausen",
    "Schwyz",
    "Solothurn",
    "St. Gallen",
    "Thurgau",
    "Ticino",
    "Uri",
    "Valais",
    "Vaud",
    "Zug",
    "Zurich",
];

const TR: &[&str] = &[
    "Adana",
    "Adıyaman",
    "Afyonkarahisar",
    "Ağrı",
    "Aksaray",
    "Amasya",
    "Ankara",
    "Antalya",
    "Ardahan",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Bartın",
    "Batman",
    "Bayburt",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakır",
    "Düzce",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkâri",
    "Hatay",
    "Iğdır",
    "Isparta",
    "Istanbul",
    "İzmir",
    "Kahramanmaraş",
    "Karabük",
    "Karaman",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kilis",
    "Kırıkkale",
    "Kırklareli",
    "Kırşehir",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Mardin",
    "Mersin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Osmaniye",
    "Rize",
    "Sakarya",
    "Samsun",
    "Şanlıurfa",
    "Siirt",
    "Sinop",
    "Sivas",
    "Şırnak",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Uşak",
    "Van",
    "Yalova",
    "Yozgat",
    "Zonguldak",
];

const UA: &[&str] = &[
    "Cherkasy",
    "Chernihiv",
    "Chernivtsi",
    "Crimea",
    "Dnipropetrovsk",
    "Donetsk",
    "Ivano-Frankivsk",
    "Kharkiv",
    "Kherson",
    "Khmelnytskyi",
    "Kiev",
    "Kirovohrad",
    "Luhansk",
    "Lviv",
    "Mykolaiv",
    "Odessa",
    "Poltava",
    "Rivne",
    "Sevastopol",
    "Sumy",
    "Ternopil",
    "Vinnytsia",
    "Volyn",
    "Zakarpattia",
    "Zaporizhzhia",
    "Zhytomyr",
];

const GB: &[&str] = &["England", "Northern Ireland", "Scotland", "Wales"];

const VA: &[&str] = &["Vatican City"];

const AX: &[&str] = &["Åland"];

const FO: &[&str] = &[
    "Eysturoy",
    "Northern Isles",
    "Sandoy",
    "Streymoy",
    "Suðuroy",
    "Vágar",
];

const GI: &[&str] = &["Gibraltar"];

const GG: &[&str] = &[
    "Alderney",
    "Castel",
    "Forest",
    "St Andrew",
    "St Martin",
    "St Peter Port",
    "St Pierre du Bois",
    "St Sampson",
    "St Saviour",
    "Sark",
    "Torteval",
    "Vale",
];

const IM: &[&str] = &["Ayre", "Garff", "Glenfaba", "Michael", "Middle", "Rushen"];

const JE: &[&str] = &[
    "Grouville",
    "St Brelade",
    "St Clement",
    "St Helier",
    "St John",
    "St Lawrence",
    "St Martin",
    "St Mary",
    "St Ouen",
    "St Peter",
    "St Saviour",
    "Trinity",
];

const SJ: &[&str] = &["Svalbard", "Jan Mayen"];

const REGIONS_BY_COUNTRY: &[(&str, &[&str])] = &[
    ("AD", AD),
    ("AL", AL),
    ("AM", AM),
    ("AT", AT),
    ("AX", AX),
    ("AZ", AZ),
    ("BA", BA),
    ("BE", BE),
    ("BG", BG),
    ("BY", BY),
    ("CA", CA),
    ("CH", CH),
    ("CY", CY),
    ("CZ", CZ),
    ("DE", DE),
    ("DK", DK),
    ("EE", EE),
    ("ES", ES),
    ("FI", FI),
    ("FO", FO),
    ("FR", FR),
    ("GB", GB),
    ("GE", GE),
    ("GG", GG),
    ("GI", GI),
    ("GR", GR),
    ("HR", HR),
    ("HU", HU),
    ("IE", IE),
    ("IM", IM),
    ("IS", IS),
    ("IT", IT),
    ("JE", JE),
    ("LI", LI),
    ("LT", LT),
    ("LU", LU),
    ("LV", LV),
    ("MC", MC),
    ("MD", MD),
    ("ME", ME),
    ("MK", MK),
    ("MT", MT),
    ("MX", MX),
    ("NL", NL),
    ("NO", NO),
    ("PL", PL),
    ("PT", PT),
    ("RO", RO),
    ("RS", RS),
    ("RU", RU),
    ("SE", SE),
    ("SI", SI),
    ("SJ", SJ),
    ("SK", SK),
    ("SM", SM),
    ("TR", TR),
    ("UA", UA),
    ("US", US),
    ("VA", VA),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mexico_has_states() {
        assert!(regions_for_country_code("MX").is_some());
        let mx = regions_for_country_code("MX").expect("MX regions");
        assert!(mx.contains(&"Jalisco"));
        assert_eq!(mx.len(), 32);
    }

    #[test]
    fn european_countries_have_regions() {
        for code in [
            "DE", "FR", "IT", "ES", "PL", "NL", "SE", "NO", "CH", "IE", "PT", "GR",
        ] {
            assert!(
                regions_for_country_code(code).is_some(),
                "missing regions for {code}"
            );
        }
    }

    #[test]
    fn unknown_country_has_no_regions() {
        assert!(regions_for_country_code("ZZ").is_none());
    }
}
