services:
  identity:
    image: mcr.microsoft.com/devcontainers/rust:1-1-bullseye
    ports:
      - "8101:8101"
      - "3000:3000"
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  redis:
    image: redis:7-alpine

  echo:
    image: erikwegner/rsecho:release-1.0.0

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    command:
      - start-dev
      - --import-realm
    network_mode: "service:identity"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8101
    volumes:
      - ../dev_realm.json:/opt/keycloak/data/import/dev_realm.json
