http:
  routers:
    keycloak:
      rule: PathPrefix(`/`)
      entryPoints:
        - keycloak
      service: keycloak
    identity:
      rule: PathPrefix(`/`)
      entryPoints:
        - identity
      service: identity
  services:
    keycloak:
      loadBalancer:
        servers:
          - url: "http://identity:8101"
    identity:
      loadBalancer:
        servers:
          - url: "http://identity:3000"
